name: education
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  provider: ^6.1.2
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  build_runner: ^2.1.7
  auto_size_text: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  timer_controller: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  custom_lint: ^0.0.16

flutter:
  uses-material-design: true
